name: Docker Image CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: env ONTPUB_ORG="oliveh" ./docker-run.sh --buildimage
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Dockerhub
      run: env ONTPUB_ORG="oliveh" ./docker-run.sh --pushimage